//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyDoanhNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class dang_ky_su_dung_hoa_don
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dang_ky_su_dung_hoa_don()
        {
            this.doanh_nghiep = new HashSet<doanh_nghiep>();
        }
    
        public int id { get; set; }
        public Nullable<bool> tu_in_hoa_don { get; set; }
        public Nullable<bool> hoa_don_dien_tu { get; set; }
        public Nullable<bool> dat_in_hoa_don { get; set; }
        public Nullable<bool> mua_hoa_don { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doanh_nghiep> doanh_nghiep { get; set; }
    }
}
