//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyDoanhNghiep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qldkdn_entity : DbContext
    {
        public qldkdn_entity()
            : base("name=tuanpa2_QuanLyDangKyDoanhNghiepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dan_toc> dan_toc { get; set; }
        public virtual DbSet<doanh_nghiep> doanh_nghiep { get; set; }
        public virtual DbSet<external_account> external_account { get; set; }
        public virtual DbSet<internal_account> internal_account { get; set; }
        public virtual DbSet<loai_hinh> loai_hinh { get; set; }
        public virtual DbSet<nganh_nghe> nganh_nghe { get; set; }
        public virtual DbSet<nhan_vien> nhan_vien { get; set; }
        public virtual DbSet<quoc_tich> quoc_tich { get; set; }
    }
}
