//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyDoanhNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class thong_tin_thue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thong_tin_thue()
        {
            this.doanh_nghiep = new HashSet<doanh_nghiep>();
        }
    
        public int id { get; set; }
        public int id_dia_chi_nhan_thong_bao_thue { get; set; }
        public bool hach_toan_doc_lap { get; set; }
        public bool bao_cao_tai_chinh_hop_nhat { get; set; }
        public int thang_bat_dau_nam_tai_chinh { get; set; }
        public int ngay_bat_dau_nam_tai_chinh { get; set; }
        public int thang_ket_thuc_nam_tai_chinh { get; set; }
        public int ngay_ket_thuc_nam_tai_chinh { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau_hoat_dong_kinh_doanh { get; set; }
        public Nullable<int> so_lao_dong_du_kien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doanh_nghiep> doanh_nghiep { get; set; }
        public virtual thongtin_diachi thongtin_diachi { get; set; }
    }
}
